name: Run Hello World

on:
  workflow_dispatch:

jobs:
  run-hello-world:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello World script
        run: python "C:\Users\sandhata\Desktop\hello.py"
